---
# Source: kube-notary/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-notary
  namespace: default
  labels:
    app.kubernetes.io/name: kube-notary
    app.kubernetes.io/instance: kube-notary
rules:
- apiGroups: [""]
  resources: ["namespaces", "namespaces/status", "secrets", "serviceaccounts", "pods", "pods/status", "pod/logs"]
  verbs: ["get", "list", "watch"]
