---
# Source: kube-notary/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-notary
  labels:
    app.kubernetes.io/name: kube-notary
    app.kubernetes.io/instance: kube-notary
