apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-notary.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-notary.fullname" . }}
  namespace: {{ .Release.Namespace }}