apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "namespaces/status", "secrets", "serviceaccounts", "pods", "pods/status", "pod/logs"]
  verbs: ["get", "list", "watch"]