apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics-port
      protocol: TCP
      name: metrics-port
  selector:
    app.kubernetes.io/name: {{ include "kube-notary.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
